### ISSUE TITLE
Popup width do not adapt to content

### ISSUE THREAD

**Issue by wippy00** [ShipBit/sveltekit-leaflet#1]
The width of the class "leaflet-popup-content" always remains at 51px regardless of what's inside.
Reading on the internet it seems to be due to the fact that the popup is created before the content is added to it. 
But I couldn't find a solution to the problem

**Comment by Shackless** [comment]
There are several ways to handle this, as described here: https://stackoverflow.com/questions/38170366/leaflet-adjust-popup-to-picture-size. You basically have to update the popup when your content is ready. The most generic and map-level approach is to this when you open the popup.

In Leaflet.svelte where you initialize your map: 

```ts
   import { tick } from 'svelte';

   map = L.map(mapElement)
      .on('popupopen', async (e) => {
         await tick(); // wait until the next frame render
         e.popup.update();
   });
```

If your popup content is loaded more lazily or resizes after loading, you might have to try the other options that call `popup.open()` whenever your content is ready.
